### ISSUE TITLE
`sls remove` does not remove additional stacks

### ISSUE THREAD

**Issue by valeeum** [nordcloud/serverless-plugin-additional-stacks#15]
Calling `sls remove` does not remove the additional stacks.

**Comment by all9lives** [comment]
@valeeum running `sls remove additionalstacks -s {stage-name}` deleted the additional stack for me.

**Comment by artoliukkonen** [comment]
This is by-design and documented functionality. To make this less confusing, we might of course add a notification for `sls remove` command saying that it does not remove additional stacks. PR for that is welcome. 

From README.md: 
> The Additional Stacks Plugin allows you to move your "permanent" resources into a separate CloudFormation stack, which is not tightly coupled with the service. If you delete your Serverless service and deploy it again from scratch, the permanent resources and their stored data remain untouched.
