### ISSUE TITLE
node 12 dependency not documented

### ISSUE THREAD

**Issue by herebebogans** [nordcloud/serverless-plugin-additional-stacks#33]
This commit  https://github.com/nordcloud/serverless-plugin-additional-stacks/commit/85cb4c7ed39c04effc8fae04693c0ab3d70d009b made the plugin dependant on node 12 as `Object.fromEntries()` was only added in node 12.

The requirement should probably be documented or declared in package.json

**Comment by kennu** [comment]
Good catch! Version 1.4.x should still work with older Node versions.

**Comment by kennu** [comment]
Added the requirement now to README and package.json.
