### ISSUE TITLE
Warning "type" property

### ISSUE THREAD

**Issue by TroyCoombs** [nordcloud/serverless-plugin-additional-stacks#40]
Recently moved up to Serverless 2.40.0 and getting this warning, which will be an error in V3,

Deprecation warning: CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
             - AdditionalStacksPlugin for "skip-additionalstacks", "stack"
            Please report this issue in plugin issue tracker.
            Starting with next major release, this will be communicated with a thrown error.
            More Info: https://www.serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA

**Comment by medikoo** [comment]
Created PR at https://github.com/nordcloud/serverless-plugin-additional-stacks/pull/42
